namespace DataAccessInterface
{
    public enum TabState
    {
        Image,
        Text
    }

    public enum PaddingRemoval
    {
        None,               // no padding removal
        Tighest,            // remove padding as much as possible, per bitmap
        Fixed               // remove padding as much as the bitmap with least padding
    }

    public enum LineWrap
    {
        AtColumn,           // After each column
        AtBitmap            // After each bitmap
    }

    public enum SpaceGeneration
    {
        AsBitmap,           // generate the space character normally
        Generated           // will be generated by driver, skip
    }

    public enum CommentStyle
    {
        C,               // c style comments - /* */
        Cpp              // C++ style - //
    }
    public enum BitLayout
    {
        RowMajor,     // '|' = 0x80,0x80,0x80  '_' = 0x00,0x00,0xFF
        ColumnMajor,  // '|' = 0xFF,0x00,0x00  '_' = 0x80,0x80,0x80
    }

    public enum ByteOrder
    {
        LsbFirst,     // Least significat bit first
        MsbFirst      // Most significat bit first
    }

    public enum ByteFormat
    {
        Binary,     // Binary
        Hex         // Hex
    }

    public enum Rotation
    {
        RotateZero,
        RotateNinety,
        RotateOneEighty,
        RotateTwoSeventy
    }

    public enum Flip
    {
        Normal,
        Flipped
    }

    public enum DescriptorFormat
    {
        DontDisplay,
        DisplayInBits,
        DisplayInBytes
    }
}
