stages:
  - build
  - test

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

build-job:
  stage: build
  image:
    name: docker/compose:latest
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker-compose -f src\TheDotFactoryChanges\aspnetcore.dockerfile build
  #  - docker-compose -f src\TheDotFactoryChanges\aspnetcore.dockerfile push
  after_script:
    - docker logout ${CI_REGISTRY}

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

integration-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."
