image:
  name: docker/compose:latest

stages:
  - build
  - test

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

build-job:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker-compose -f src/TheDotFactoryChanges/docker-compose-unit-test.yml build
    - docker-compose -f src/TheDotFactoryChanges/docker-compose-integration-test.yml build
    - docker-compose -f src/TheDotFactoryChanges/docker-compose-e2e-test.yml build
  after_script:
    - docker logout ${CI_REGISTRY}

unit-test-job:
  stage: test
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker-compose -f src/TheDotFactoryChanges/docker-compose-unit-test.yml up -d
  after_script:
    - docker logout ${CI_REGISTRY}

integration-test-job:
  stage: test
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker-compose -f src/TheDotFactoryChanges/docker-compose-integration-test.yml up -d
  after_script:
    - docker logout ${CI_REGISTRY}

e2e-test-job:
  stage: test
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker-compose -f src/TheDotFactoryChanges/docker-compose-e2e-test.yml up -d
  after_script:
    - docker logout ${CI_REGISTRY}
