using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

using NUnit.Allure.Core;
using NUnit.Framework;

using DataAccessSQLServer;
using Service;

namespace CommonITCase
{
    [AllureNUnit]
    public class ConvertionFromTemplateIT
    {
        [Test]
        public async Task ConvertionFromTemplateTest()
        {
            string serverAddr = "localhost,1433";
            if (Environment.OSVersion.Platform == PlatformID.Unix)
            {
                serverAddr = "webapp_sqlserver";
            }
            var dbName = "the_dotfactory_test";
            Common.CreateTestDatabase(dbName, serverAddr);
            var snapshotName = "testdb";
            var snapshotPath = $@"/var/opt/mssql/data/{snapshotName}.ss";
            Common.CreateDatabaseSnapshot(dbName, serverAddr, snapshotName, snapshotPath);
            try
            {
                var contextFactory = new DbContextFactory();
                var repoFactory = new RepositoryFactory(contextFactory, serverAddr, dbName, "SA", "P@ssword", false);
                var textRenderer = new WinFormsTextRendererAdapter();
                var authService = new AuthService.AuthService(repoFactory);
                var cvtService = new ConverterService(repoFactory, textRenderer);
                await authService.RegistrateUser("user_001", "password", "password");
                await authService.LoginUser("user_001", "password");
                int fontId;
                if (Environment.OSVersion.Platform == PlatformID.Unix)
                {
                    fontId = await cvtService.AddFont(new DataAccessInterface.Font
                    {
                        Name = "DejaVu Sans",
                        Size = 10,
                    });
                }
                else
                {
                    fontId = await cvtService.AddFont(new DataAccessInterface.Font
                    {
                        Name = "Arial",
                        Size = 10,
                    });
                }

                cvtService.SetInputText("1");
                await cvtService.SetCurrentFont(fontId);
                var cfgId = await cvtService.CreateConfig(new DataAccessInterface.Configuration());
                await cvtService.SetCurrentConfig(cfgId);

                await cvtService.ConvertFont(true);

                var sourceText = cvtService.GetOutputSourceText();
                var headerText = cvtService.GetOutputHeaderText();
                if (Environment.OSVersion.Platform == PlatformID.Unix)
                {
                    //Assert.AreEqual(sourceText, "#include \"peg.hpp\"\nROMDATA WORD AutoGenerated__offset_table[2] = {\n0x0, 0x3, };\nROMDATA UCHAR AutoGenerated__data_table[] = {\n0x20, \n0x60, \n0xA0, \n0x20, \n0x20, \n0x20, \n0x20, \n\n};\n\nPegFont AutoGenerated_ = {1, 7, 0, 7, 1, 0, 0, \n(WORD*)AutoGenerated__offset_table, NULL,\n(UCHAR *) AutoGenerated__data_table};\n");
                    //Assert.AreEqual(headerText, "// '1' (3 pixels wide)//\n//   #     \n//  ##     \n// # #     \n//   #     \n//   #     \n//   #     \n//   #     \n");
                }
                else
                {
                    //Assert.AreEqual(sourceText, "#include \"peg.hpp\"\nROMDATA WORD AutoGenerated__offset_table[2] = {\n0x0, 0x3, };\nROMDATA UCHAR AutoGenerated__data_table[] = {\n0x20, \n0x60, \n0xA0, \n0x20, \n0x20, \n0x20, \n0x20, \n\n};\n\nPegFont AutoGenerated_ = {1, 7, 0, 7, 1, 0, 0, \n(WORD*)AutoGenerated__offset_table, NULL,\n(UCHAR *) AutoGenerated__data_table};\n");
                    //Assert.AreEqual(headerText, "// '1' (3 pixels wide)//\n//   #     \n//  ##     \n// # #     \n//   #     \n//   #     \n//   #     \n//   #     \n");
                }
            }
            finally
            {
                Common.RestoreDatabaseBySnapshot(dbName, serverAddr, snapshotName);
            }
        }
    }
}
