namespace ConverterServiceTest
{
    public class ConverterServiceTest
    {
        [Test]
        public void UpdateFontNullArgumentTest()
        {

        }

        public void UpdateBitmapNullArgumentTest()
        {

        }

        [Test]
        public void UpdateTabStateNullArgumentTest()
        {

        }

        [Test]
        public void SetInputTextNullArgumentTest()
        {

        }

        [Test]
        public void SetPegFontTextNullArgumentTest()
        {

        }

        [Test]
        public void ConvertFontNotSelectedFontTest()
        {

        }

        [Test]
        public void ConvertFontNotSelectedConfigurationTest()
        {

        }

        [Test]
        public void ConvertFontImageTest()
        {

        }

        [Test]
        public void ConvertFontPegFontTest()
        {

        }

        [Test]
        public void ConvertFontNotPegFontTest()
        {

        }

        [Test]
        public void AddTextInsertionTest()
        {

        }

        [Test]
        public void RemoveTextInsertionTest()
        {

        }

        [Test]
        public void GetTextInsertionTest()
        {

        }

        [Test]
        public void GetTextInsertionsTest()
        {

        }

        [Test]
        public void SetImageTextTest()
        {

        }

        [Test]
        public void CreateConfigTest()
        {

        }

        [Test]
        public void DeleteConfigTest()
        {

        }

        [Test]
        public void UpdateConfigTest()
        {

        }

        [Test]
        public void GetConfigByIdTest()
        {

        }

        [Test]
        public void GetCurrentConfigTest()
        {

        }

        [Test]
        public void SetCurrentConfigTest()
        {

        }

        [Test]
        public void GetConfigurationsTest()
        {

        }

        [Test]
        public void UpdateConfigurationsTest()
        {

        }

        [Test]
        public void GetCurrentBitmapTest()
        {

        }

        [Test]
        public void GetCurrentFontTest()
        {

        }

        [Test]
        public void GetFontNamesTest()
        {

        }

        [Test]
        public void GetConvertionsTest()
        {

        }

        [Test]
        public void GetConvertionByIdTest()
        {

        }

        [Test]
        public void AddConvertionTest()
        {

        }

        [Test]
        public void GetOutputSourceTextTest()
        {

        }

        [Test]
        public void GetOutputHeaderTextTest()
        {

        }

        [Test]
        public void ConvertFontFromAutogeneratedTextTest()
        {

        }
    }
}